feat: removing the chess games from the log
chesslablab/chess-server pull request #310
Opened 2024-07-25 18:55 UTC by KartikWatts

Closes #272 

This PR removed the logs for chess games.

2024-07-27 15:32 UTC, programarivm commented on src/Socket/RatchetClientStorage.php
> -                $this->logger->info('Sent message', [
It will still be convenient to log the command names.

```php
$this->logger->info('Sent message', [
    'id' => $id,
    'cmd' => array_keys($res),
]);
```

2024-07-27 15:33 UTC, programarivm commented on src/Socket/WorkermanClientStorage.php
> -                $this->logger->info('Sent message', [
```php
$this->logger->info('Sent message', [
    'id' => $id,
    'cmd' => array_keys($res),
]);
```

2024-07-27 15:34 UTC, programarivm commented on src/Socket/WorkermanClientStorage.php
> -                $this->logger->info('Sent message', [
```php
$this->logger->info('Sent message', [
    'ids' => $ids,
    'cmd' => array_keys($res),
]);
```

2024-07-27 15:35 UTC, programarivm requested changes
It will still be convenient to log the command names.

2024-07-28 07:43 UTC, KartikWatts reviewed
@programarivm Thanks a lot for the details, so basically I have reverted the commit: https://github.com/chesslablab/chess-server/pull/265/commits/caf8a33df2889280a5f3affa1364ab06d544e367, this would achieve the requirements. Rebased the PR.

2024-07-28 14:42 UTC, programarivm approved these changes
Excellent, thanks!

2024-07-28 14:43 UTC, merged